/*
 * Simple user API
 *
 * This is a user API
 *
 * API version: 1.0.0
 * Contact: kollisreekanth@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type User struct {

	Id string `json:"id"`

	Username string `json:"username"`

	Password string `json:"password"`

	CreatedDate time.Time `json:"createdDate"`
}
