/*
 * HPE API
 *
 * API's for HPE User Interface
 *
 * API version: 1.0.1
 * Contact: kollisreekanth@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type UserModel struct {

	Id string `json:"id,omitempty"`

	Username string `json:"username"`

	Password string `json:"password"`

	CreatedDate time.Time `json:"createdDate,omitempty"`
}
