/*
 * HPE API
 *
 * API's for HPE User Interface
 *
 * API version: 1.0.1
 * Contact: kollisreekanth@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ErrorModel struct {

	Code int32 `json:"code"`

	Message string `json:"message"`
}
