/*
 * HPE API
 *
 * API's for HPE User Interface
 *
 * API version: 1.0.1
 * Contact: kollisreekanth@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LoginResponseModel struct {

	Id string `json:"id,omitempty"`

	Username string `json:"username"`

	Token string `json:"token"`
}
