/*
 * HPE API
 *
 * API's for HPE User Interface
 *
 * API version: 1.0.1
 * Contact: kollisreekanth@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/ADP9529/hpe/1.0.1/",
		Index,
	},

	Route{
		"Login",
		strings.ToUpper("Post"),
		"/ADP9529/hpe/1.0.1/login",
		Login,
	},

	Route{
		"AddUser",
		strings.ToUpper("Post"),
		"/ADP9529/hpe/1.0.1/user",
		AddUser,
	},

	Route{
		"GetAllUsers",
		strings.ToUpper("Get"),
		"/ADP9529/hpe/1.0.1/user",
		GetAllUsers,
	},
}
