name: Create Pull Request
on:
  create: 
    branches:
      - new
  push:
    branches: 
      - new
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Create PR Branch
        run: |
          curl -X POST -u ksrikanthreddy:d44e3c7d898273fe11b29c1fdc053715a4ce9d25 -i https://api.github.com/repos/ksrikanthreddy/testSwaggerHubAdvanced/pulls -d "{\"title\":\"my_login\",\"body\":\"my_password\",\"head\":\"ksrikanthreddy:new\",\"base\":\"master\"}"