name: Create Pull Request
on:
  create: 
    branches:
      - swagger
  push:
    branches: 
      - swagger
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Create PR Branch
        run: |
          curl -X POST -u ksrikanthreddy:${{ secrets.GITHUB_TOKEN }} -i https://api.github.com/repos/ksrikanthreddy/testSwaggerHubAdvanced/pulls -d "{\"title\":\"SwaggerHub Changes\",\"body\":\"SwaggerHub Changes\",\"head\":\"ksrikanthreddy:swagger\",\"base\":\"master\"}"